on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: caendesilva/hyde-composite-test-action@v0.0.2
        with:
          who-to-greet: 'Caen'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
